apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qpwk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-qpwk@sha256:a29a1edf3d0a4f43ec650e5462cb13225dc0dcf6de6eb03c312fa815eddaa132
        name: my-nodejs
        resources: {}
status: {}
